import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ResponsiveContainer} from 'recharts';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
async function api(path:string,init?:RequestInit){const r=await fetch(API+path,init); if(!r.ok) throw new Error(await r.text()); return r.json();}
function App(){
 const [projects,setProjects]=useState<any[]>([]),[project,setProject]=useState<any>(),[datasets,setDatasets]=useState<any[]>([]),[models,setModels]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[metrics,setMetrics]=useState<any[]>([]),[target,setTarget]=useState('target'),[name,setName]=useState('CPU Classifier'),[status,setStatus]=useState('');
 const load=async()=>{setProjects(await api('/projects'));setRuns(await api('/training/runs'));};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(project){api('/datasets?project_id='+project.id).then(setDatasets);api('/models?project_id='+project.id).then(setModels)}},[project]);
 useEffect(()=>{const id=runs[0]?.id;if(!id)return; const t=setInterval(async()=>{const rr=await api('/training/runs');setRuns(rr);setMetrics(await api('/training/runs/'+id+'/metrics'));},1000);return()=>clearInterval(t)},[runs[0]?.id]);
 const createProject=async()=>{const p=await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Real ML Project'})});setProject(p);await load()};
 const upload=async(e:any)=>{const f=e.target.files?.[0];if(!f||!project)return;const fd=new FormData();fd.append('file',f);fd.append('project_id',project.id);const d=await api('/datasets',{method:'POST',body:fd});setDatasets(x=>[d,...x])};
 const createModel=async()=>{if(!project)return;const m=await api('/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:project.id,name,task:'classification',hidden_layers:[64,32],activation:'relu',dropout:0})});setModels(x=>[m,...x])};
 const train=async()=>{if(!project||!datasets[0]||!models[0])return setStatus('Create a project, upload a dataset, and create a model first.');const r=await api('/training/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:project.id,dataset_id:datasets[0].id,model_id:models[0].id,target,task:'classification',hidden_layers:[64,32],activation:'relu',dropout:0,optimizer:'adam',learning_rate:.001,weight_decay:0,batch_size:32,epochs:10,train_ratio:.7,val_ratio:.15,test_ratio:.15,seed:42,cpu_workers:1,threads:1})});await api('/training/runs/'+r.id+'/start',{method:'POST'});setStatus('Training started: '+r.id);await load()};
 const latest=runs[0]; const chart=metrics.filter(x=>x.split==='train').map(x=>({epoch:x.epoch,loss:x.loss,metric:x.metric}));
 return <div className="app"><aside><h1>ForgeML</h1><p>Real CPU training platform</p><nav><span>Dashboard</span><span>Datasets</span><span>Models</span><span>Training Runs</span><span>Evaluation</span><span>Inference</span><span>System</span></nav></aside><main><header><div><small>LOCAL AI/ML WORKSPACE</small><h2>Training control center</h2></div><button onClick={createProject}>+ New Project</button></header>{status&&<div className="notice">{status}</div>}<section className="grid"><div className="card"><h3>Project</h3>{project?<b>{project.name}</b>:<p>No project selected. Create one to begin.</p>}</div><div className="card"><h3>Dataset</h3><input type="file" accept=".csv,.json,.jsonl" onChange={upload}/><p>{datasets[0]?`${datasets[0].name} · ${datasets[0].rows} rows`: 'No dataset uploaded'}</p></div><div className="card"><h3>Model Builder</h3><input value={name} onChange={e=>setName(e.target.value)} aria-label="model name"/><button onClick={createModel}>Create real MLP</button><p>{models[0]?.name||'No model'}</p></div><div className="card"><h3>Target column</h3><input value={target} onChange={e=>setTarget(e.target.value)}/><button onClick={train}>Start CPU training</button></div></section><section className="card"><div className="row"><div><h3>Live training</h3><p>Status: <b>{latest?.status||'IDLE'}</b></p></div><div><span>CPU {latest?'worker process':'ready'}</span></div></div><ResponsiveContainer width="100%" height={300}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="epoch"/><YAxis/><Tooltip/><Line type="monotone" dataKey="loss" dot={false}/></LineChart></ResponsiveContainer></section><section className="card"><h3>Training runs</h3><table><thead><tr><th>ID</th><th>Status</th><th>Error</th></tr></thead><tbody>{runs.slice(0,10).map(r=><tr key={r.id}><td>{r.id.slice(0,8)}</td><td>{r.status}</td><td>{r.error||'—'}</td></tr>)}</tbody></table></section></main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
